# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ehosta <ehosta@student.42lyon.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/05/19 15:02:31 by ehosta            #+#    #+#              #
#    Updated: 2025/05/19 15:08:31 by ehosta           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

override SOURCES_DIR	:=	src/
override INCLUDE_DIR	:=	include/
HEADERS	:=
SOURCES	:=	megaphone

SOURCE	:=	